[tool.poetry]
name = "itmo-math-stat"
version = "0.1.0"
description = ""
authors = ["nikolai hilkovich <n.hilkovich@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
